[package]
name = "nominator-v2"
description = "TON Nominator pool v2 smart contract"
version = "2.0.0"
license = "MIT"

[toolchain]
acton = "1.2.0"

[contracts.Pool]
display-name = "Pool"
src = "contracts/Pool.tolk"
depends = ["PayoutItem", "Proxy"]

[contracts.PayoutItem]
display-name = "PayoutItem"
src = "contracts/PayoutItem.tolk"

[contracts.Proxy]
display-name = "Proxy"
src= "contracts/Proxy.tolk"

[contracts.Elector]
display-name = "Elector"
src="contracts/elector-code.boc"
types="contracts/Elector.types.tolk"

[test]

[fmt]
width = 100
ignore = []

[lint]
exclude = ["tests/*.tolk"]

[scripts]
deploy-emulation = "acton script scripts/deploy.tolk"
deploy-testnet = "acton script scripts/deploy.tolk --net testnet"
init-pool-emulation = "acton script scripts/init-pool.tolk"
init-pool-testnet = "acton script scripts/init-pool.tolk --net testnet"
add-validator-emulation = "acton script scripts/add-validator.tolk"
add-validator-testnet = "acton script scripts/add-validator.tolk --net testnet"
remove-validator-emulation = "acton script scripts/remove-validator.tolk"
remove-validator-testnet = "acton script scripts/remove-validator.tolk --net testnet"
update-nominators-whitelist-emulation = "acton script scripts/update-nominators-whitelist.tolk"
update-nominators-whitelist-testnet = "acton script scripts/update-nominators-whitelist.tolk --net testnet"
owner-withdrawal-emulation = "acton script scripts/owner-withdrawal.tolk"
owner-withdrawal-testnet = "acton script scripts/owner-withdrawal.tolk --net testnet"
add-funds-emulation = "acton script scripts/add-funds.tolk"
add-funds-testnet = "acton script scripts/add-funds.tolk --net testnet"
update-validator-limits-emulation = "acton script scripts/update-validator-limits.tolk"
update-validator-limits-testnet = "acton script scripts/update-validator-limits.tolk --net testnet"
update-nominator-limits-emulation = "acton script scripts/update-nominator-limits.tolk"
update-nominator-limits-testnet = "acton script scripts/update-nominator-limits.tolk --net testnet"
update-validator-limit-emulation = "acton script scripts/update-validator-limit.tolk"
update-validator-limit-testnet = "acton script scripts/update-validator-limit.tolk --net testnet"
pool-info-emulation = "acton script scripts/pool-info.tolk"
pool-info-testnet = "acton script scripts/pool-info.tolk --net testnet"

[import-mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
scripts = "scripts"
tests = "tests"
wrappers = "wrappers"

# Check full Acton.toml reference and all available keys:
# https://ton-blockchain.github.io/acton/docs/acton-toml
