const POOL_MIN_STORAGE = grams("10")
const REFUND_THRESHOLD = grams("1")
const MAX_RECOVERY_VALUE = grams("1")
const DEPOSIT_GAS = grams("0.2")
const WITHDRAWAL_GAS = DEPOSIT_GAS
const NEW_VALIDATOR_FEE = grams("0.1")
const PROXY_MIN_STORAGE = grams("10")
const PROXY_INIT_VALUE = grams("0.1")
const PAYOUT_ITEM_BALANCE = grams("0.05")
const PAYOUT_CHAIN_START = grams("0.011")

const RECOVER_STAKE_OK_GAS: int = 50000
const SELF_UPDATE_VSET_GAS = 22000
